apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp_rc
spec:
  replicas: 2
  selector:
    app: myjavaapp
  template:
    metadata:
      name: myjavaapp
      labels:
        app: myjavaapp
    spec:
      containers:
        - name: myjavacontainer
          image: nginx
          ports:
            - containerPort: 80
