apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-svc
  labels:
     app: nginx
     
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 3001
    protocol: TCP
  selector:
      app:  nginx